#!/bin/bash
# Inspired by Svelte Kit & Fuma Nama

# Function to get absolute filename
get_abs_filename() {
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

DIR=$(get_abs_filename $(dirname "$0"))
TMP=$(get_abs_filename "$DIR/../node_modules/.tmp")

mkdir -p $TMP
cd $TMP

# Set global Git configuration
git config --global user.email "me@honghong.me"
git config --global user.name "tszhong0411"

rm -rf eslint-config-inspector
git clone --depth 1 --single-branch --branch main https://github.com/tszhong0411/eslint-config-inspector.git

cd eslint-config-inspector
pnpm eslint-config-inspector build
cp -r $DIR/../.eslint-config-inspector/* $TMP/eslint-config-inspector

# Create a README.md file
cat <<EOF > README.md
# eslint-config-inspector

This is a ESLint config inspector generated by [@tszhong0411/eslint-config](https://github.com/tszhong0411/honghong.me/tree/main/packages/eslint-config)
EOF


git add -A
git commit -m "version $npm_package_version"

git push https://github.com/tszhong0411/eslint-config-inspector.git main -f
